### ISSUE TITLE
Create New user

### ISSUE THREAD

**Issue by gr8rehanna** [luiscib3r/Telezon-S3#2]
How can we create keys, user?

In api/auth/signup what we have to pass in header?

**Comment by luiscib3r** [comment]
Hi friend. This is a pretty old project, I don't know if it still works correctly but I'll try to help you. 

In the file: `app/crud/user.py`. The function `crud_create_user` is responsible for creating the user's keys at the time of registration.

```python
if not data_user.access_key_id:
        data_user.access_key_id = ''.join(random.choice(
            string.ascii_letters + string.digits) for _ in range(16))

if not data_user.secret_key:
        data_user.secret_key = ''.join(random.choice(
            string.ascii_letters + string.digits) for _ in range(16))
```

I don't remember why this is checking that the keys do not exist previously but in the payload of the `api/auth/signup` endpoint it is not necessary to pass them, they are simply created when registering the user.

Then you use those keys with the s3 client of your choice. In the README there is an example using boto3. The keys are checked in the file `app/s3/utils.py`.

```python


async def aws_sig_verify(bucket: Bucket, request: Request):
    body = await request.body()
    headers = dict(**request.headers)
    headers['X-Amz-Date'] = headers.get('x-amz-date', '')
    path = str(request.url).replace(str(request.base_url), '/')

    v = AWSSigV4Verifier(
        request_method=request.method,
        uri_path=path,
        query_string=str(request.query_params),
        headers=headers,
        body=body,
        region="us-east-1",
        service="s3",
        key_mapping={bucket.owner.access_key_id: bucket.owner.secret_key},
        timestamp_mismatch=None
    )
    try:
        v.verify()
        return True
    except InvalidSignatureError as e:
        print('Invalid signature: %s', e)
    except Exception as e:
        print('Unable to verify request: %s', e)
```

This attempts to simulate the process that the real S3 service does.

I hope this helps you. 🤗

**Comment by gr8rehanna** [comment]
Thanks mate.'

it worked but as u said its very old code.
i upgraded to pyrogram2.0.xx now its working but only problem it has not uploading larger files
using multi-part


Thanks.

**Comment by gr8rehanna** [comment]
Also maybe someone in future asks same question.
Here is simple and easy explanation

Using Below PHP code can create users.
```
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'http://172.24.93.195:8000/api/auth/signup',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
    "username": "username", // Bucket will be created with same name 🪣 
    "email": "admin@admin.com",
    "password": "securepassword123"
}
',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```

**Comment by luiscib3r** [comment]
I'll take a look at this project and see if I can update it and review the file upload endpoint to support multipart form.

**Comment by gr8rehanna** [comment]
For me it worked 👍 

Few issues like new telegram channels has some issues.
I dont know exactly but.

Suppose we upload 10 files then it stops sending new files unless any user or another bot sends something/message in channel then it uploads.
I was checking this to add as an node on minio and worked fine for me.
using minio for my mastodon instance.

Thanks for awesome project.

**Comment by luiscib3r** [comment]
Hi again @gr8rehanna, can you take a look at the update I made on the main branch?

**Comment by amjiddader** [comment]
Sure, 
Will deploy again & let you know.
Also , how about simple admin tool? 

add admin email password in env.
then either from cli or webui i.e python3 admin.py --help
127.0.0.1:8000/admin 

manage things like, 
list add modify delete ban users
list edit delete create buckets

**Comment by amjiddader** [comment]
Thanks for updating

**Comment by gr8rehanna** [comment]
Will deploy again & let you know.
Also , how about simple admin tool? 

add admin email password in env.
then either from cli or webui i.e python3 admin.py --help
127.0.0.1:8000/admin 

manage things like, 
list add modify delete ban users
list edit delete create buckets

**Comment by luiscib3r** [comment]
@gr8rehanna By going to http://127.0.0.1:8000/docs you will be able to see the list of endpoints that allow you to manage users, buckets, etc. To create an admin user you have to go into the DB and edit the role. I am going to enable the admin password to be set in an environment variable when doing the first deployment of the API.
